/**
 * WebRTC camera server: RTSP cameras -> MediaMTX -> WebRTC in the browser.
 *
 *   npm start            (from pc/)
 *   npm run camera       (from the repo root)
 *
 * Cameras come from the MongoDB registry when MONGODB_URI is set (manage them
 * with `npm run cameras`), otherwise from the single RTSP_URL in .env. Video
 * never touches the database -- it only stores which cameras exist.
 */
import './env.js';
import express from 'express';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { which, installHint } from './which.js';
import { dbConfigured, getCameras } from './db.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const MTX_BIN = path.join(ROOT, 'bin', 'mediamtx.exe');
const MTX_CONF = path.join(ROOT, 'bin', 'mediamtx.generated.yml');

const PORT = Number(process.env.PORT || 8080);
const VIEW_PASSWORD = process.env.VIEW_PASSWORD || '';
const TRANSCODE_BITRATE = process.env.TRANSCODE_BITRATE || '3000k';

/**
 * Shared secret for the /<name>.mp4 endpoints. Machines consuming those URLs
 * cannot do the cookie login, so they authenticate with ?key=<STREAM_KEY>.
 * Unset means the .mp4 endpoints are off entirely -- an open camera feed should
 * never be something you get by forgetting to set a variable.
 */
const STREAM_KEY = process.env.STREAM_KEY || '';

// MediaMTX's own ports. Bound to localhost -- everything reaches them through
// this server, so the password gate cannot be bypassed by hitting them directly.
const MTX_WEBRTC_PORT = 8889;
const MTX_API_PORT = 9997;
const MTX_RTSP_PORT = 8554;

if (!fs.existsSync(MTX_BIN)) {
  console.error(`\n  mediamtx.exe not found at ${MTX_BIN}`);
  console.error('  Run: npm run setup\n');
  process.exit(1);
}

let shuttingDown = false;
let lastError = '';

// ---------------------------------------------------------------------------
// Camera list
// ---------------------------------------------------------------------------

/** @type {{name:string,label:string,rtspUrl:string,transport:string,transcode:boolean}[]} */
let cameras = [];

async function loadCameras() {
  if (dbConfigured()) {
    const list = await getCameras();
    if (list.length) return list;
    console.error('\n  The camera registry is empty. Add one:');
    console.error('    npm run cameras -- add cam "Camera 1" rtsp://user:pass@ip:554/path\n');
    process.exit(1);
  }

  // No database: fall back to the single .env camera so the zero-setup path
  // keeps working.
  const url = process.env.RTSP_URL;
  if (!url || url.includes('username:password')) {
    console.error('\n  Neither MONGODB_URI nor RTSP_URL is set in .env\n');
    process.exit(1);
  }
  return [{
    name: 'cam',
    label: 'Camera',
    rtspUrl: url,
    transport: process.env.RTSP_TRANSPORT || 'tcp',
    transcode: true,
  }];
}

const maskUrl = (u) => u.replace(/\/\/[^@/]*@/, '//***:***@');

// ---------------------------------------------------------------------------
// MediaMTX config
//
// Per camera:
//   - transcode: true   raw-<name> pulls the camera; <name> is published into
//                       by an ffmpeg we spawn (see startTranscode) that fixes
//                       the pixel format. Needed for cameras that emit
//                       full-range yuvj420p, which browsers silently refuse to
//                       decode: connection up, megabytes flowing, grey screen.
//   - transcode: false  <name> pulls the camera directly and its H264 passes
//                       through untouched at near-zero CPU. Use for cameras
//                       that emit standard yuv420p.
// ---------------------------------------------------------------------------

function writeConfig() {
  const quote = (s) => `'${s.replace(/'/g, "''")}'`;

  const paths = cameras.map((cam) => {
    if (!cam.transcode) {
      return [
        `  ${cam.name}:`,
        `    source: ${quote(cam.rtspUrl)}`,
        `    sourceProtocol: ${cam.transport}`,
        `    sourceOnDemand: no`,
      ].join('\n');
    }
    return [
      `  raw-${cam.name}:`,
      `    source: ${quote(cam.rtspUrl)}`,
      `    sourceProtocol: ${cam.transport}`,
      // NOT sourceOnDemand: on-demand dials the camera only once a viewer is
      // already connecting, but the page waits for "ready" before connecting.
      // The page waits for the camera, the camera waits for the page.
      `    sourceOnDemand: no`,
      `  ${cam.name}:`,
    ].join('\n');
  });

  const yaml = `# Generated by src/webrtc.js on every start. Do not edit; edit the camera
# registry (npm run cameras) or .env instead.
logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: 127.0.0.1:${MTX_API_PORT}

# RTSP on localhost only: the loopback the transcode ffmpegs read from and
# publish back into. Not reachable from the network.
rtsp: yes
rtspAddress: 127.0.0.1:${MTX_RTSP_PORT}
protocols: [tcp]

rtmp: no
hls: no
srt: no

webrtc: yes
webrtcAddress: 127.0.0.1:${MTX_WEBRTC_PORT}
webrtcAllowOrigin: '*'
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302

paths:
${paths.join('\n')}
`;

  fs.writeFileSync(MTX_CONF, yaml);
}

// ---------------------------------------------------------------------------
// MediaMTX process
// ---------------------------------------------------------------------------

let mtx = null;

function startMediaMtx() {
  writeConfig();

  mtx = spawn(MTX_BIN, [MTX_CONF], { cwd: ROOT, windowsHide: true });

  mtx.stdout.on('data', (d) => {
    const line = d.toString().trim();
    if (line && /err|fail/i.test(line)) {
      lastError = line.slice(0, 300);
      console.error('[mediamtx]', line);
    }
  });
  mtx.stderr.on('data', (d) => {
    const line = d.toString().trim();
    if (line) console.error('[mediamtx]', line);
  });

  mtx.on('close', (code) => {
    mtx = null;
    if (shuttingDown) return;
    console.error(`\n  mediamtx exited (${code}) - restarting in 3s\n`);
    setTimeout(startMediaMtx, 3000);
  });
}

// ---------------------------------------------------------------------------
// Transcodes: raw-<name> (whatever the camera emits) -> <name> (yuv420p that
// browsers actually decode). One ffmpeg per camera that needs it.
// ---------------------------------------------------------------------------

/** name -> { proc, startedAt, restarts } */
const transcodes = new Map();

function transcodeArgs(cam) {
  return [
    '-hide_banner',
    '-loglevel', 'error',
    '-rtsp_transport', 'tcp',
    '-i', `rtsp://127.0.0.1:${MTX_RTSP_PORT}/raw-${cam.name}`,

    // The scale filter does the real work. `-pix_fmt yuv420p` ALONE IS NOT
    // ENOUGH: x264 carries the source's full-range flag through and the output
    // comes back out yuvj420p / color_range=pc, unchanged. Only
    // scale=out_range=tv actually converts the range. Verified with ffprobe.
    '-vf', 'scale=out_range=tv:out_color_matrix=bt709',
    '-pix_fmt', 'yuv420p',
    '-color_range', 'tv',

    // Level 4.0, not 3.1: 3.1 caps out near 720p and x264 refuses 1080p25
    // outright ("MB rate > level limit"), encoding nothing.
    '-c:v', 'libx264',
    '-profile:v', 'baseline',
    '-level', '4.0',
    '-preset', 'ultrafast',
    '-tune', 'zerolatency',
    '-b:v', TRANSCODE_BITRATE,
    '-g', '50',
    '-bf', '0',
    '-an',

    '-f', 'rtsp',
    '-rtsp_transport', 'tcp',
    `rtsp://127.0.0.1:${MTX_RTSP_PORT}/${cam.name}`,
  ];
}

function startTranscode(cam) {
  if (shuttingDown || transcodes.get(cam.name)?.proc) return;

  const bin = which('ffmpeg');
  if (!bin) {
    lastError = installHint('ffmpeg').replace(/\n\s*/g, ' ');
    console.error(`\n  ${lastError}\n`);
    return;
  }

  const state = transcodes.get(cam.name) ?? { proc: null, startedAt: 0, restarts: 0 };
  state.startedAt = Date.now();
  state.proc = spawn(bin, transcodeArgs(cam), { windowsHide: true });
  transcodes.set(cam.name, state);

  state.proc.stderr.on('data', (d) => {
    const line = d.toString().trim();
    if (!line) return;
    lastError = `[${cam.name}] ` + line.split('\n').pop().slice(0, 250);
    console.error(`[transcode:${cam.name}]`, line);
  });

  state.proc.on('close', (code) => {
    state.proc = null;
    if (shuttingDown) return;

    // Back off if it dies immediately (a real fault); reconnect fast if it ran.
    const lived = Date.now() - state.startedAt;
    if (lived > 15_000) state.restarts = 0;
    else state.restarts++;

    const delay = Math.min(2000 * 2 ** Math.max(0, state.restarts - 1), 30_000);
    console.error(`[transcode:${cam.name}] exited (${code}) - restarting in ${delay / 1000}s`);
    setTimeout(() => startTranscode(cam), delay);
  });
}

/** Wait for a camera's raw path to come up in MediaMTX, then transcode it. */
async function armTranscode(cam) {
  for (let i = 0; i < 60 && !shuttingDown; i++) {
    try {
      const r = await fetch(`http://127.0.0.1:${MTX_API_PORT}/v3/paths/get/raw-${cam.name}`);
      if (r.ok && (await r.json()).ready) {
        startTranscode(cam);
        return;
      }
    } catch {
      // MediaMTX still coming up.
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  console.error(`\n  Camera "${cam.name}" never became ready - check its RTSP URL.\n`);
}

// ---------------------------------------------------------------------------
// Auth: one shared password, exchanged for a signed cookie.
// ---------------------------------------------------------------------------

const SESSION_SECRET = crypto.randomBytes(32).toString('hex');

function issueToken() {
  const expires = Date.now() + 7 * 24 * 60 * 60 * 1000;
  const sig = crypto.createHmac('sha256', SESSION_SECRET).update(String(expires)).digest('hex');
  return `${expires}.${sig}`;
}

function tokenIsValid(token) {
  if (typeof token !== 'string') return false;
  const [expires, sig] = token.split('.');
  if (!expires || !sig) return false;
  if (Number(expires) < Date.now()) return false;
  const expected = crypto.createHmac('sha256', SESSION_SECRET).update(expires).digest('hex');
  const a = Buffer.from(sig);
  const b = Buffer.from(expected);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

function parseCookies(header = '') {
  return Object.fromEntries(
    header.split(';').map((c) => {
      const i = c.indexOf('=');
      if (i < 0) return ['', ''];
      return [c.slice(0, i).trim(), decodeURIComponent(c.slice(i + 1).trim())];
    }),
  );
}

function requireAuth(req, res, next) {
  if (!VIEW_PASSWORD) return next();
  const { session } = parseCookies(req.headers.cookie);
  if (tokenIsValid(session)) return next();
  res.status(401).json({ error: 'unauthorized' });
}

// ---------------------------------------------------------------------------
// HTTP
// ---------------------------------------------------------------------------

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', true);
app.use(express.json());

app.get('/api/config', (req, res) => {
  const { session } = parseCookies(req.headers.cookie);
  res.json({
    requiresPassword: Boolean(VIEW_PASSWORD),
    authenticated: !VIEW_PASSWORD || tokenIsValid(session),
    mode: 'webrtc',
  });
});

app.post('/api/login', (req, res) => {
  if (!VIEW_PASSWORD) return res.json({ ok: true });

  const supplied = Buffer.from(String(req.body?.password ?? ''));
  const actual = Buffer.from(VIEW_PASSWORD);
  const ok = supplied.length === actual.length && crypto.timingSafeEqual(supplied, actual);

  if (!ok) return res.status(401).json({ error: 'Wrong password' });

  // Secure only over HTTPS -- set unconditionally, the cookie never comes back
  // over plain HTTP on localhost and a correct password still locks you out.
  const isHttps = req.secure || req.headers['x-forwarded-proto'] === 'https';

  res.setHeader(
    'Set-Cookie',
    [
      `session=${issueToken()}`,
      'HttpOnly',
      'Path=/',
      'Max-Age=604800',
      'SameSite=Lax',
      isHttps ? 'Secure' : null,
    ].filter(Boolean).join('; '),
  );

  res.json({ ok: true });
});

/** The picker: every camera and whether it currently has video. */
app.get('/api/cameras', requireAuth, async (req, res) => {
  const out = [];
  for (const cam of cameras) {
    let ready = false;
    try {
      const r = await fetch(`http://127.0.0.1:${MTX_API_PORT}/v3/paths/get/${cam.name}`);
      if (r.ok) ready = Boolean((await r.json()).ready);
    } catch {
      // MediaMTX not up yet.
    }
    out.push({ name: cam.name, label: cam.label, ready });
  }
  res.json({ cameras: out, error: out.some((c) => c.ready) ? '' : lastError });
});

/**
 * WHEP signalling, proxied to MediaMTX so the password gate covers the video.
 * Only the SDP handshake passes through here; media flows peer-to-peer.
 */
async function handleWhep(req, res, camName) {
  // The name lands in a URL to MediaMTX: accept only names we actually loaded.
  const cam = cameras.find((c) => c.name === camName);
  if (!cam) return res.status(404).json({ error: 'no such camera' });

  try {
    const upstream = await fetch(`http://127.0.0.1:${MTX_WEBRTC_PORT}/${cam.name}/whep`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/sdp' },
      body: req.body,
    });

    const answer = await upstream.text();

    if (!upstream.ok) {
      console.error(`[whep:${cam.name}] mediamtx said`, upstream.status, answer.slice(0, 200));
      return res.status(upstream.status).send(answer);
    }

    // Location points at MediaMTX's session resource for ICE trickle; rewrite
    // it through our proxy or the browser tries a port it cannot reach.
    const loc = upstream.headers.get('location');
    if (loc) res.setHeader('Location', `/webrtc/session?u=${encodeURIComponent(loc)}`);

    res.setHeader('Content-Type', 'application/sdp');
    res.send(answer);
  } catch (err) {
    console.error(`[whep:${cam.name}] proxy failed:`, err.message);
    res.status(502).json({ error: 'stream unavailable' });
  }
}

const sdpBody = express.text({ type: '*/*', limit: '1mb' });

app.post('/webrtc/whep/:cam', requireAuth, sdpBody, (req, res) =>
  handleWhep(req, res, req.params.cam),
);

/** Back-compat: the pre-registry player posted here with no camera name. */
app.post('/webrtc/whep', requireAuth, sdpBody, (req, res) => {
  if (!cameras.length) return res.status(404).json({ error: 'no cameras' });
  handleWhep(req, res, cameras[0].name);
});

/** ICE candidate trickle, patched through to the MediaMTX session URL. */
app.patch('/webrtc/session', requireAuth, express.text({ type: '*/*', limit: '1mb' }), async (req, res) => {
  const target = req.query.u;
  if (typeof target !== 'string') return res.status(400).end();

  try {
    const upstream = await fetch(new URL(target, `http://127.0.0.1:${MTX_WEBRTC_PORT}`), {
      method: 'PATCH',
      headers: {
        'Content-Type': req.headers['content-type'] ?? 'application/trickle-ice-sdpfrag',
        ...(req.headers['if-match'] ? { 'If-Match': req.headers['if-match'] } : {}),
      },
      body: req.body,
    });
    res.status(upstream.status).send(await upstream.text());
  } catch {
    res.status(502).end();
  }
});

// ---------------------------------------------------------------------------
// /<name>.mp4 -- the live feed as a plain HTTP video URL, for anything that
// won't speak WebRTC: a bare <video src>, VLC, an NVR, another site.
//
// Fragmented MP4 (frag_keyframe+empty_moov) is what makes this work. A normal
// MP4 puts its index (the moov atom) at the end, so it cannot be written until
// the file is complete -- useless for a stream that never ends. Fragmented MP4
// emits self-contained chunks instead, and the response simply never closes.
//
// The source is the transcoded path, not raw-<name>: it is already the yuv420p
// that browsers will decode, so this copies it (-c copy) at near-zero CPU
// rather than encoding again per viewer.
// ---------------------------------------------------------------------------

/** Constant-time compare so the key can't be guessed a character at a time. */
function keyIsValid(supplied) {
  const a = Buffer.from(String(supplied ?? ''));
  const b = Buffer.from(STREAM_KEY);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

app.get('/:cam.mp4', (req, res) => {
  if (!STREAM_KEY) {
    return res.status(404).json({ error: 'set STREAM_KEY in .env to enable .mp4 URLs' });
  }

  // A browser cookie is fine too, so the feed still plays in a logged-in tab.
  const { session } = parseCookies(req.headers.cookie);
  const authed = (VIEW_PASSWORD && tokenIsValid(session)) || keyIsValid(req.query.key);
  if (!authed) return res.status(401).json({ error: 'unauthorized' });

  const cam = cameras.find((c) => c.name === req.params.cam);
  if (!cam) return res.status(404).json({ error: 'no such camera' });

  const bin = which('ffmpeg');
  if (!bin) return res.status(500).json({ error: 'ffmpeg not installed' });

  const ff = spawn(bin, [
    '-hide_banner',
    '-loglevel', 'error',
    '-rtsp_transport', 'tcp',
    '-i', `rtsp://127.0.0.1:${MTX_RTSP_PORT}/${cam.name}`,
    '-c:v', 'copy',
    '-an',
    '-f', 'mp4',
    // empty_moov: start writing immediately, no index up front.
    // frag_keyframe: cut a fragment at each keyframe, so players can begin
    // mid-stream. default_base_moof: what Chrome/Safari's MSE expects.
    '-movflags', 'frag_keyframe+empty_moov+default_base_moof',
    'pipe:1',
  ], { windowsHide: true });

  res.setHeader('Content-Type', 'video/mp4');
  res.setHeader('Cache-Control', 'no-store');

  ff.stdout.pipe(res);
  ff.stderr.on('data', (d) => console.error(`[mp4:${cam.name}]`, d.toString().trim()));

  // One ffmpeg per viewer: it must die with the request, or every disconnect
  // leaks a process that keeps pulling video forever.
  const kill = () => ff.kill('SIGKILL'); // SIGTERM is a no-op for ffmpeg on Windows
  res.on('close', kill);
  ff.on('close', () => res.end());
});

app.use(express.static(path.join(ROOT, 'public-webrtc')));

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

cameras = await loadCameras();

console.log(`\n  Cameras (${cameras.length}):`);
for (const cam of cameras) {
  console.log(`    ${cam.name.padEnd(14)} ${cam.transcode ? 'transcode' : 'passthrough'}  ${maskUrl(cam.rtspUrl)}`);
}
console.log(`  Source:   ${dbConfigured() ? 'MongoDB registry' : '.env (single camera)'}`);
console.log(`  Mode:     WebRTC (sub-second)`);
console.log(`  Local:    http://localhost:${PORT}`);
console.log(`  Password: ${VIEW_PASSWORD ? 'on' : 'OFF - anyone with the URL can watch'}`);
console.log(`\n  For the public URL, in a second terminal:  npm run tunnel\n`);

const server = app.listen(PORT, '0.0.0.0', () => {
  startMediaMtx();
  for (const cam of cameras) {
    if (cam.transcode) armTranscode(cam);
  }
});

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    console.error(`\n  Port ${PORT} is already in use.`);
    console.error('  Another server is still running - close it, or set PORT in .env\n');
    process.exit(1);
  }
  throw err;
});

for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    shuttingDown = true;
    for (const t of transcodes.values()) t.proc?.kill('SIGKILL');
    mtx?.kill();
    process.exit(0);
  });
}
