import './env.js';
import express from 'express';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { which } from './which.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const MTX_BIN = path.join(ROOT, 'bin', 'mediamtx.exe');
const MTX_CONF = path.join(ROOT, 'bin', 'mediamtx.generated.yml');

const RTSP_URL = process.env.RTSP_URL;
const PORT = Number(process.env.PORT || 8080);
const RTSP_TRANSPORT = process.env.RTSP_TRANSPORT || 'tcp';
const VIEW_PASSWORD = process.env.VIEW_PASSWORD || '';

// MediaMTX's own ports. Not exposed publicly -- everything reaches them through
// this server, so the password gate cannot be bypassed by hitting them directly.
const MTX_WEBRTC_PORT = 8889;
const MTX_API_PORT = 9997;
const MTX_RTSP_PORT = 8554;

const TRANSCODE_BITRATE = process.env.TRANSCODE_BITRATE || '3000k';

if (!RTSP_URL || RTSP_URL.includes('username:password')) {
  console.error('\n  RTSP_URL is not set. Put your camera URL in .env\n');
  process.exit(1);
}

if (!fs.existsSync(MTX_BIN)) {
  console.error(`\n  mediamtx.exe not found at ${MTX_BIN}`);
  console.error('  Run: npm run setup\n');
  process.exit(1);
}

const safeUrl = RTSP_URL.replace(/\/\/[^@/]*@/, '//***:***@');

// ---------------------------------------------------------------------------
// MediaMTX
//
// It pulls the camera over RTSP and republishes it as WebRTC. No transcoding
// (the camera's H.264 is what browsers want anyway) and no segmenting, so there
// is no playlist to go stale and no 2s chunk boundary to wait on. That is where
// the sub-second latency comes from, and why the whole class of HLS bugs --
// missing segments, stale playlists, 404 retry loops -- simply cannot occur.
// ---------------------------------------------------------------------------

function writeConfig() {
  // YAML: the RTSP URL can contain characters that need quoting, and it holds
  // the camera password, so single-quote it and escape any embedded quotes.
  const quoted = `'${RTSP_URL.replace(/'/g, "''")}'`;

  const yaml = `# Generated by src/webrtc.js on every start. Do not edit; edit .env instead.
logLevel: info
logDestinations: [stdout]

# Everything is proxied through the Node server, which owns the password gate.
# Binding to localhost keeps these ports off the network entirely.
api: yes
apiAddress: 127.0.0.1:${MTX_API_PORT}

# RTSP on localhost only. Not for viewers -- it is the loopback the transcode
# step below reads from and writes back into. Bound to 127.0.0.1 so it is not
# reachable from the network.
rtsp: yes
rtspAddress: 127.0.0.1:${MTX_RTSP_PORT}
protocols: [tcp]

rtmp: no
hls: no
srt: no

webrtc: yes
webrtcAddress: 127.0.0.1:${MTX_WEBRTC_PORT}
webrtcAllowOrigin: '*'
# Let the browser and MediaMTX find each other directly over the LAN, and fall
# back to STUN for anything else. No TURN server, so a viewer on a network that
# blocks direct UDP will not connect -- see README.
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302

paths:
  # The camera, pulled straight from RTSP. Not served to browsers directly --
  # see the 'cam' path below for why.
  camraw:
    source: ${quoted}
    sourceProtocol: ${RTSP_TRANSPORT}

    # NOT sourceOnDemand. On-demand only dials the camera once a viewer is
    # already connecting, so /api/stream/status could never report ready before
    # someone watched -- and the page waits for ready before it connects. That
    # deadlocks: the page waits for the camera, the camera waits for the page.
    sourceOnDemand: no

  # What browsers actually read. Published into by the transcode ffmpeg that this
  # server spawns (see startTranscode) -- an empty path here just accepts it.
  #
  # The camera encodes H264 with pix_fmt yuvj420p -- the full-range JPEG variant
  # of YUV420. Browser H264 decoders expect limited-range yuv420p. Handed
  # yuvj420p they accept the RTP, report no error, and decode nothing: the peer
  # connection reads "connected", megabytes arrive, and the screen stays grey.
  # ffprobe decodes it fine, which is what makes this so easy to misdiagnose.
  #
  # MediaMTX forwards the stream untouched, so the only fix is to re-encode into
  # a pixel format browsers will decode.
  cam:
`;

  fs.writeFileSync(MTX_CONF, yaml);
}

let mtx = null;
let mtxReady = false;
let lastError = '';
let shuttingDown = false;

function startMediaMtx() {
  writeConfig();

  mtx = spawn(MTX_BIN, [MTX_CONF], { cwd: ROOT, windowsHide: true });

  mtx.stdout.on('data', (d) => {
    const line = d.toString().trim();
    if (!line) return;

    if (/listener opened|ready/i.test(line)) mtxReady = true;
    if (/err|fail/i.test(line)) {
      lastError = line.slice(0, 300);
      console.error('[mediamtx]', line);
    }
  });

  mtx.stderr.on('data', (d) => {
    const line = d.toString().trim();
    if (line) console.error('[mediamtx]', line);
  });

  mtx.on('close', (code) => {
    mtx = null;
    if (shuttingDown) return;
    console.error(`\n  mediamtx exited (${code}) - restarting in 3s\n`);
    setTimeout(startMediaMtx, 3000);
  });
}

// ---------------------------------------------------------------------------
// Transcode: camraw (yuvj420p, unplayable) -> cam (yuv420p, what browsers want)
//
// Run from here rather than MediaMTX's runOnInit: runOnInit fires when a path is
// created, and a path with no source never initializes, so the transcode simply
// never started. Spawning it ourselves also means its errors are visible instead
// of swallowed -- which is how the level-3.1 mistake below stayed hidden.
// ---------------------------------------------------------------------------

let transcode = null;
let transcodeStartedAt = 0;
let transcodeRestarts = 0;

function transcodeArgs() {
  return [
    '-hide_banner',
    '-loglevel', 'error',
    '-rtsp_transport', 'tcp',
    '-i', `rtsp://127.0.0.1:${MTX_RTSP_PORT}/camraw`,

    // The scale filter is what actually converts the range. `-pix_fmt yuv420p`
    // ALONE IS NOT ENOUGH: x264 carries the source's full-range flag through and
    // the output comes back out as yuvj420p / color_range=pc, unchanged. Only
    // scale=out_range=tv converts it. Verified with ffprobe; don't drop this.
    '-vf', 'scale=out_range=tv:out_color_matrix=bt709',
    '-pix_fmt', 'yuv420p',
    '-color_range', 'tv',

    // Level 4.0, not 3.1: 3.1 caps out around 720p, and x264 refuses 1080p25
    // outright ("MB rate > level limit") and encodes nothing.
    '-c:v', 'libx264',
    '-profile:v', 'baseline',
    '-level', '4.0',
    '-preset', 'ultrafast',
    '-tune', 'zerolatency',
    '-b:v', TRANSCODE_BITRATE,
    '-g', '50',
    '-bf', '0',
    '-an',

    '-f', 'rtsp',
    '-rtsp_transport', 'tcp',
    `rtsp://127.0.0.1:${MTX_RTSP_PORT}/cam`,
  ];
}

function startTranscode() {
  if (transcode || shuttingDown) return;

  const bin = which('ffmpeg');
  if (!bin) {
    lastError = 'ffmpeg not found. Install it: winget install Gyan.FFmpeg';
    console.error(`\n  ${lastError}\n`);
    return;
  }

  transcodeStartedAt = Date.now();
  transcode = spawn(bin, transcodeArgs(), { windowsHide: true });

  transcode.stderr.on('data', (d) => {
    const line = d.toString().trim();
    if (!line) return;
    lastError = line.split('\n').pop().slice(0, 300);
    console.error('[transcode]', line);
  });

  transcode.on('close', (code) => {
    transcode = null;
    if (shuttingDown) return;

    // Back off if it dies immediately (a real fault); reconnect fast if it ran.
    const lived = Date.now() - transcodeStartedAt;
    if (lived > 15_000) transcodeRestarts = 0;
    else transcodeRestarts++;

    const delay = Math.min(2000 * 2 ** Math.max(0, transcodeRestarts - 1), 30_000);
    console.error(`[transcode] exited (${code}) - restarting in ${delay / 1000}s`);
    setTimeout(startTranscode, delay);
  });
}

// ---------------------------------------------------------------------------
// Auth (same shared-password scheme as the HLS server)
// ---------------------------------------------------------------------------

const SESSION_SECRET = crypto.randomBytes(32).toString('hex');

function issueToken() {
  const expires = Date.now() + 7 * 24 * 60 * 60 * 1000;
  const sig = crypto.createHmac('sha256', SESSION_SECRET).update(String(expires)).digest('hex');
  return `${expires}.${sig}`;
}

function tokenIsValid(token) {
  if (typeof token !== 'string') return false;
  const [expires, sig] = token.split('.');
  if (!expires || !sig) return false;
  if (Number(expires) < Date.now()) return false;
  const expected = crypto.createHmac('sha256', SESSION_SECRET).update(expires).digest('hex');
  const a = Buffer.from(sig);
  const b = Buffer.from(expected);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

function parseCookies(header = '') {
  return Object.fromEntries(
    header.split(';').map((c) => {
      const i = c.indexOf('=');
      if (i < 0) return ['', ''];
      return [c.slice(0, i).trim(), decodeURIComponent(c.slice(i + 1).trim())];
    }),
  );
}

function requireAuth(req, res, next) {
  if (!VIEW_PASSWORD) return next();
  const { session } = parseCookies(req.headers.cookie);
  if (tokenIsValid(session)) return next();
  res.status(401).json({ error: 'unauthorized' });
}

// ---------------------------------------------------------------------------
// HTTP
// ---------------------------------------------------------------------------

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', true);
app.use(express.json());

app.get('/api/config', (req, res) => {
  const { session } = parseCookies(req.headers.cookie);
  res.json({
    requiresPassword: Boolean(VIEW_PASSWORD),
    authenticated: !VIEW_PASSWORD || tokenIsValid(session),
    mode: 'webrtc',
  });
});

app.post('/api/login', (req, res) => {
  if (!VIEW_PASSWORD) return res.json({ ok: true });

  const supplied = Buffer.from(String(req.body?.password ?? ''));
  const actual = Buffer.from(VIEW_PASSWORD);
  const ok = supplied.length === actual.length && crypto.timingSafeEqual(supplied, actual);

  if (!ok) return res.status(401).json({ error: 'Wrong password' });

  // Secure only over HTTPS: Cloudflare terminates TLS and forwards the header.
  // Setting it unconditionally would stop the cookie coming back over plain
  // HTTP on localhost, locking the viewer out with a correct password.
  const isHttps = req.secure || req.headers['x-forwarded-proto'] === 'https';

  res.setHeader(
    'Set-Cookie',
    [
      `session=${issueToken()}`,
      'HttpOnly',
      'Path=/',
      'Max-Age=604800',
      'SameSite=Lax',
      isHttps ? 'Secure' : null,
    ]
      .filter(Boolean)
      .join('; '),
  );

  res.json({ ok: true });
});

app.get('/api/stream/status', requireAuth, async (req, res) => {
  try {
    const r = await fetch(`http://127.0.0.1:${MTX_API_PORT}/v3/paths/get/cam`);
    if (r.ok) {
      const info = await r.json();
      return res.json({ ready: Boolean(info.ready), error: '' });
    }
  } catch {
    // MediaMTX still starting up.
  }
  res.json({ ready: false, error: lastError });
});

/**
 * Proxy the WebRTC signalling handshake to MediaMTX.
 *
 * The browser POSTs an SDP offer here and gets an SDP answer back; after that
 * the media itself flows peer-to-peer over UDP, not through this server. Only
 * the handshake is proxied, which is what lets the password gate cover WebRTC
 * without putting the video through Node.
 */
app.post('/webrtc/whep', requireAuth, express.text({ type: '*/*', limit: '1mb' }), async (req, res) => {
  try {
    const upstream = await fetch(`http://127.0.0.1:${MTX_WEBRTC_PORT}/cam/whep`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/sdp' },
      body: req.body,
    });

    const answer = await upstream.text();

    if (!upstream.ok) {
      console.error('[whep] mediamtx said', upstream.status, answer.slice(0, 200));
      return res.status(upstream.status).send(answer);
    }

    // The Location header points at the session resource for ICE trickle. It is
    // a MediaMTX-local URL, so rewrite it through our proxy or the browser will
    // try to reach a port it cannot see.
    const loc = upstream.headers.get('location');
    if (loc) res.setHeader('Location', `/webrtc/session?u=${encodeURIComponent(loc)}`);

    res.setHeader('Content-Type', 'application/sdp');
    res.send(answer);
  } catch (err) {
    console.error('[whep] proxy failed:', err.message);
    res.status(502).json({ error: 'stream unavailable' });
  }
});

/** ICE candidate trickle, patched through to the MediaMTX session URL. */
app.patch('/webrtc/session', requireAuth, express.text({ type: '*/*', limit: '1mb' }), async (req, res) => {
  const target = req.query.u;
  if (typeof target !== 'string') return res.status(400).end();

  try {
    const upstream = await fetch(new URL(target, `http://127.0.0.1:${MTX_WEBRTC_PORT}`), {
      method: 'PATCH',
      headers: {
        'Content-Type': req.headers['content-type'] ?? 'application/trickle-ice-sdpfrag',
        ...(req.headers['if-match'] ? { 'If-Match': req.headers['if-match'] } : {}),
      },
      body: req.body,
    });
    res.status(upstream.status).send(await upstream.text());
  } catch (err) {
    res.status(502).end();
  }
});

app.use(express.static(path.join(ROOT, 'public-webrtc')));

const server = app.listen(PORT, '0.0.0.0', () => {
  console.log(`\n  Camera:   ${safeUrl}`);
  console.log(`  Mode:     WebRTC (sub-second)`);
  console.log(`  Local:    http://localhost:${PORT}`);
  console.log(`  Password: ${VIEW_PASSWORD ? 'on' : 'OFF - anyone with the URL can watch'}`);
  console.log(`\n  For a public URL, in a second terminal:`);
  console.log(`    npm run tunnel\n`);
});

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    console.error(`\n  Port ${PORT} is already in use.`);
    console.error('  Another server is still running - close it, or set PORT in .env\n');
    process.exit(1);
  }
  throw err;
});

startMediaMtx();

// The transcode reads camraw from MediaMTX, so it has to wait for MediaMTX's
// RTSP listener to be up. Poll rather than guess at a fixed delay.
(async function waitThenTranscode() {
  for (let i = 0; i < 30; i++) {
    try {
      const r = await fetch(`http://127.0.0.1:${MTX_API_PORT}/v3/paths/get/camraw`);
      if (r.ok && (await r.json()).ready) {
        startTranscode();
        return;
      }
    } catch {
      // MediaMTX still coming up.
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  console.error('\n  Camera never became ready. Check RTSP_URL, or run: npm run probe\n');
})();

for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    shuttingDown = true;
    transcode?.kill('SIGKILL');
    mtx?.kill();
    process.exit(0);
  });
}
