import './env.js';
import express from 'express';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const MTX_BIN = path.join(ROOT, 'bin', 'mediamtx.exe');
const MTX_CONF = path.join(ROOT, 'bin', 'mediamtx.generated.yml');

const RTSP_URL = process.env.RTSP_URL;
const PORT = Number(process.env.PORT || 8080);
const RTSP_TRANSPORT = process.env.RTSP_TRANSPORT || 'tcp';
const VIEW_PASSWORD = process.env.VIEW_PASSWORD || '';

// MediaMTX's own ports. Not exposed publicly -- everything reaches them through
// this server, so the password gate cannot be bypassed by hitting them directly.
const MTX_WEBRTC_PORT = 8889;
const MTX_API_PORT = 9997;

if (!RTSP_URL || RTSP_URL.includes('username:password')) {
  console.error('\n  RTSP_URL is not set. Put your camera URL in .env\n');
  process.exit(1);
}

if (!fs.existsSync(MTX_BIN)) {
  console.error(`\n  mediamtx.exe not found at ${MTX_BIN}`);
  console.error('  Run: npm run setup\n');
  process.exit(1);
}

const safeUrl = RTSP_URL.replace(/\/\/[^@/]*@/, '//***:***@');

// ---------------------------------------------------------------------------
// MediaMTX
//
// It pulls the camera over RTSP and republishes it as WebRTC. No transcoding
// (the camera's H.264 is what browsers want anyway) and no segmenting, so there
// is no playlist to go stale and no 2s chunk boundary to wait on. That is where
// the sub-second latency comes from, and why the whole class of HLS bugs --
// missing segments, stale playlists, 404 retry loops -- simply cannot occur.
// ---------------------------------------------------------------------------

function writeConfig() {
  // YAML: the RTSP URL can contain characters that need quoting, and it holds
  // the camera password, so single-quote it and escape any embedded quotes.
  const quoted = `'${RTSP_URL.replace(/'/g, "''")}'`;

  const yaml = `# Generated by src/webrtc.js on every start. Do not edit; edit .env instead.
logLevel: info
logDestinations: [stdout]

# Everything is proxied through the Node server, which owns the password gate.
# Binding to localhost keeps these ports off the network entirely.
api: yes
apiAddress: 127.0.0.1:${MTX_API_PORT}

rtsp: no
rtmp: no
hls: no
srt: no

webrtc: yes
webrtcAddress: 127.0.0.1:${MTX_WEBRTC_PORT}
webrtcAllowOrigin: '*'
# Let the browser and MediaMTX find each other directly over the LAN, and fall
# back to STUN for anything else. No TURN server, so a viewer on a network that
# blocks direct UDP will not connect -- see README.
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302

paths:
  cam:
    source: ${quoted}
    sourceProtocol: ${RTSP_TRANSPORT}

    # NOT sourceOnDemand. On-demand only dials the camera once a viewer is
    # already connecting, so /api/stream/status could never report ready before
    # someone watched -- and the page waits for ready before it connects. That
    # deadlocks: the page waits for the camera, the camera waits for the page.
    #
    # Always-on also means the stream is live the instant a viewer arrives
    # rather than after a 2-3s dial. Bandwidth is free here (nothing is metered),
    # so the only cost is a continuous pull from the camera.
    sourceOnDemand: no
`;

  fs.writeFileSync(MTX_CONF, yaml);
}

let mtx = null;
let mtxReady = false;
let lastError = '';

function startMediaMtx() {
  writeConfig();

  mtx = spawn(MTX_BIN, [MTX_CONF], { cwd: ROOT, windowsHide: true });

  mtx.stdout.on('data', (d) => {
    const line = d.toString().trim();
    if (!line) return;

    if (/listener opened|ready/i.test(line)) mtxReady = true;
    if (/err|fail/i.test(line)) {
      lastError = line.slice(0, 300);
      console.error('[mediamtx]', line);
    }
  });

  mtx.stderr.on('data', (d) => {
    const line = d.toString().trim();
    if (line) console.error('[mediamtx]', line);
  });

  mtx.on('close', (code) => {
    mtx = null;
    if (shuttingDown) return;
    console.error(`\n  mediamtx exited (${code}) - restarting in 3s\n`);
    setTimeout(startMediaMtx, 3000);
  });
}

// ---------------------------------------------------------------------------
// Auth (same shared-password scheme as the HLS server)
// ---------------------------------------------------------------------------

const SESSION_SECRET = crypto.randomBytes(32).toString('hex');

function issueToken() {
  const expires = Date.now() + 7 * 24 * 60 * 60 * 1000;
  const sig = crypto.createHmac('sha256', SESSION_SECRET).update(String(expires)).digest('hex');
  return `${expires}.${sig}`;
}

function tokenIsValid(token) {
  if (typeof token !== 'string') return false;
  const [expires, sig] = token.split('.');
  if (!expires || !sig) return false;
  if (Number(expires) < Date.now()) return false;
  const expected = crypto.createHmac('sha256', SESSION_SECRET).update(expires).digest('hex');
  const a = Buffer.from(sig);
  const b = Buffer.from(expected);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

function parseCookies(header = '') {
  return Object.fromEntries(
    header.split(';').map((c) => {
      const i = c.indexOf('=');
      if (i < 0) return ['', ''];
      return [c.slice(0, i).trim(), decodeURIComponent(c.slice(i + 1).trim())];
    }),
  );
}

function requireAuth(req, res, next) {
  if (!VIEW_PASSWORD) return next();
  const { session } = parseCookies(req.headers.cookie);
  if (tokenIsValid(session)) return next();
  res.status(401).json({ error: 'unauthorized' });
}

// ---------------------------------------------------------------------------
// HTTP
// ---------------------------------------------------------------------------

const app = express();
app.disable('x-powered-by');
app.set('trust proxy', true);
app.use(express.json());

app.get('/api/config', (req, res) => {
  const { session } = parseCookies(req.headers.cookie);
  res.json({
    requiresPassword: Boolean(VIEW_PASSWORD),
    authenticated: !VIEW_PASSWORD || tokenIsValid(session),
    mode: 'webrtc',
  });
});

app.post('/api/login', (req, res) => {
  if (!VIEW_PASSWORD) return res.json({ ok: true });

  const supplied = Buffer.from(String(req.body?.password ?? ''));
  const actual = Buffer.from(VIEW_PASSWORD);
  const ok = supplied.length === actual.length && crypto.timingSafeEqual(supplied, actual);

  if (!ok) return res.status(401).json({ error: 'Wrong password' });

  // Secure only over HTTPS: Cloudflare terminates TLS and forwards the header.
  // Setting it unconditionally would stop the cookie coming back over plain
  // HTTP on localhost, locking the viewer out with a correct password.
  const isHttps = req.secure || req.headers['x-forwarded-proto'] === 'https';

  res.setHeader(
    'Set-Cookie',
    [
      `session=${issueToken()}`,
      'HttpOnly',
      'Path=/',
      'Max-Age=604800',
      'SameSite=Lax',
      isHttps ? 'Secure' : null,
    ]
      .filter(Boolean)
      .join('; '),
  );

  res.json({ ok: true });
});

app.get('/api/stream/status', requireAuth, async (req, res) => {
  try {
    const r = await fetch(`http://127.0.0.1:${MTX_API_PORT}/v3/paths/get/cam`);
    if (r.ok) {
      const info = await r.json();
      return res.json({ ready: Boolean(info.ready), error: '' });
    }
  } catch {
    // MediaMTX still starting up.
  }
  res.json({ ready: false, error: lastError });
});

/**
 * Proxy the WebRTC signalling handshake to MediaMTX.
 *
 * The browser POSTs an SDP offer here and gets an SDP answer back; after that
 * the media itself flows peer-to-peer over UDP, not through this server. Only
 * the handshake is proxied, which is what lets the password gate cover WebRTC
 * without putting the video through Node.
 */
app.post('/webrtc/whep', requireAuth, express.text({ type: '*/*', limit: '1mb' }), async (req, res) => {
  try {
    const upstream = await fetch(`http://127.0.0.1:${MTX_WEBRTC_PORT}/cam/whep`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/sdp' },
      body: req.body,
    });

    const answer = await upstream.text();

    if (!upstream.ok) {
      console.error('[whep] mediamtx said', upstream.status, answer.slice(0, 200));
      return res.status(upstream.status).send(answer);
    }

    // The Location header points at the session resource for ICE trickle. It is
    // a MediaMTX-local URL, so rewrite it through our proxy or the browser will
    // try to reach a port it cannot see.
    const loc = upstream.headers.get('location');
    if (loc) res.setHeader('Location', `/webrtc/session?u=${encodeURIComponent(loc)}`);

    res.setHeader('Content-Type', 'application/sdp');
    res.send(answer);
  } catch (err) {
    console.error('[whep] proxy failed:', err.message);
    res.status(502).json({ error: 'stream unavailable' });
  }
});

/** ICE candidate trickle, patched through to the MediaMTX session URL. */
app.patch('/webrtc/session', requireAuth, express.text({ type: '*/*', limit: '1mb' }), async (req, res) => {
  const target = req.query.u;
  if (typeof target !== 'string') return res.status(400).end();

  try {
    const upstream = await fetch(new URL(target, `http://127.0.0.1:${MTX_WEBRTC_PORT}`), {
      method: 'PATCH',
      headers: {
        'Content-Type': req.headers['content-type'] ?? 'application/trickle-ice-sdpfrag',
        ...(req.headers['if-match'] ? { 'If-Match': req.headers['if-match'] } : {}),
      },
      body: req.body,
    });
    res.status(upstream.status).send(await upstream.text());
  } catch (err) {
    res.status(502).end();
  }
});

app.use(express.static(path.join(ROOT, 'public-webrtc')));

const server = app.listen(PORT, '0.0.0.0', () => {
  console.log(`\n  Camera:   ${safeUrl}`);
  console.log(`  Mode:     WebRTC (sub-second)`);
  console.log(`  Local:    http://localhost:${PORT}`);
  console.log(`  Password: ${VIEW_PASSWORD ? 'on' : 'OFF - anyone with the URL can watch'}`);
  console.log(`\n  For a public URL, in a second terminal:`);
  console.log(`    npm run tunnel\n`);
});

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    console.error(`\n  Port ${PORT} is already in use.`);
    console.error('  Another server is still running - close it, or set PORT in .env\n');
    process.exit(1);
  }
  throw err;
});

startMediaMtx();

let shuttingDown = false;

for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    shuttingDown = true;
    mtx?.kill();
    process.exit(0);
  });
}
